language: node_js
node_js:
  - '11'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
install:
  - yarn
before_script:
  - npx cypress verify
script:
  - yarn test
after_success:
  - npx semantic-release
