version: 2.1
orbs:
  cypress: cypress-io/cypress@1.5.1
jobs:
  release:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: npx semantic-release
workflows:
  build:
    jobs:
      - cypress/run:
          name: 'main'
          start: 'npm test'
      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - main
