version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          yarn: true
          build: 'yarn'
      - cypress/run:
          name: 'Chrome'
          yarn: true
          requires:
            - cypress/install
          executor: cypress/browsers-chrome69
          browser: chrome
