version: 2.1
orbs:
  cypress: cypress-io/cypress@1.5.1
jobs:
  release:
    executor: cypress/base-10
    steps:
      - attach_workspace:
          at: ~/
      - run: npx semantic-release
workflows:
  build:
    jobs:
      - cypress/run:
          start: 'npm test'
      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - 1 machine
