version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          yarn: true
          build: 'yarn'
      - cypress/run:
          yarn: true
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 4
          group: 'all tests'
          start: 'yarn test'
